config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users, skip: [:sessions]
# 	as :user do
# 	  get 'signin', to: 'devise/sessions#new', as: :new_user_session
# 	  post 'signin', to: 'devise/sessions#create', as: :user_session
# 	  match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
# 	end
	
#   resources :users
#   resources :products
#     resources :orders, only: [:index, :show, :create, :destroy, :new, :edit ]

#   get 'static_pages/about'

#   get 'static_pages/contact'

#   get 'static_pages/index'
#   root 'static_pages#landing_page'

#   post 'static_pages/thank_you'
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end
Rails.application.routes.draw do

devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  root 'static_pages#landing_page'
  
  resources :products do
  resources :comments
  end
   resources :orders
  resources :users
  resources :payments

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/index'
  post 'static_pages/thank_you'
  post 'payments/create'
  get 'payments/create'
  get 'products/index'
  mount ActionCable.server => '/cable'

 # get '/products/:id', to: 'products#show'

  # default route
  # may go away in future versions of Rails
  # get ':controller (/:action (/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :product
    belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  #skip_before_filter  :verify_authenticity_token MAKES it vulnurable for attacks
  protect_from_forgery with: :null_session
  respond_to :json, :html

  def index
    @orders = Order.all.to_json(:include => [{:product => {:only => :name}}, {:user => {:only => :email}}])
    respond_with @orders
  end

  def show
    @order = Order.find(params[:id]).to_json(:include => [{:product => {:only => :name}}, {:user => {:only => :email}}])
    respond_with @order
  end

  def new
  end

  def create
    @order = Order.create(order_params)
    respond_with @order
  end

  # def update
  #   respond_with Order.update(params[:id], params[:order])
  # end

  def destroy
    respond_with Order.destroy(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:product_id, :user_id, :total)
  end

end

app/views/orders/_form.html.erb
<h4>
  <%= form_with(model: order, local: true) do |form| %>  
  <% if @order.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@order.errors.count, "error") %> prohibited this product from being saved:</h2>
    <ul>
      <% @order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="container col-sm-12 col-md-6 form-group">
    <div class="form-group has-success">
      <%= form.label :name, class:"col-2 col-form-label"  %>
      <%= form.text_field :name, class:"form-control", type:"text", placeholder:"Bike Model", id:"inputSuccess1" %>
    </div>

    <div class="field">
      <%= form.label :lastname, class:"col-2 col-form-label"  %>
      <%= form.text_field :lastname, class:"form-control", type:"text", placeholder:"Lastname", id:"example-text-input" %>
    </div>

    <div class="field">
      <%= form.label :description, class:"col-2 col-form-label"  %>
      <%= form.text_area :description, class:"form-control", type:"text", placeholder:"Description", id:"example-text-input" %>
    </div>
  </div>

  <div class="container col-sm-12 col-md-6 form-group">
  <div class="field">
    <%= form.label :product_id, class:"col-2 col-form-label" %>
    <div class="input-group"> 
      <span class="input-group-addon">PID</span>
      <%= form.text_field :product_id, class:"form-control currency", placeholder:"1-100"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-default" %>
  </div>

  <div>
    <%= link_to 'Back', orders_path, class:"btn btn-default" %>
  </div>

  <% end %>
  
</h4>

app/views/orders/_order.html.erb
<% cache order do %>

	<div class="col-xs-12 col-sm-4 col-md-3">

	        <div class="order_grid_box">
		        <h3><%= link_to(order.name,order_path(order)) %></h3>
		        <p><strong>Name: </strong><%= order.name %></p>
		        <p><strong>Lastname: </strong>$<%= order.lastname %></p>
		        <%= link_to ('<u>More Details</u>').html_safe, order_path(order) %>
	    	</div>

        <%= link_to 'Show /', order %>
    	<%= link_to 'Edit /', edit_order_path(order) %>
     	<%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %>
     	<br><br><br><br>

	</div><!-- /col -->

<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div ng-controller="OrdersCtrl">
  <h1>Orders</h1>

  <form class="form-inline" ng-submit="addOrder()">
    <strong>Add order: </strong>

    <input type="number" step="0.01" ng-model="newOrder.total" class="form-control" placeholder="Total">

    <select ng-model="newOrder.product_id" class="form-control">
      <option value="" disabled selected>Select a product</option>
      <option ng-repeat="product in products" value="{{product.id}}">{{product.name}}</option>
    </select>
    <!-- <input type="number" ng-model="newOrder.user_id"> -->

    <input type="submit" value="+" class="btn btn-success">
  </form>

  <table class="table table-hover">
    <thead>
      <td>Order ID</td>
      <td>Total</td>
      <td>Product</td>
      <td></td>
    </thead>
    <tbody>
      <tr ng-repeat="order in orders | orderBy:'-id':reverse">
        <td>
          {{order.id}}
        </td>
        <td>
          <strong>{{order.total | currency}}</strong>
        </td>
        <td>
          {{order.product.name}}
          <small ng-show="order.user.email" class="text-muted"><br>-{{order.user.email}}</small>
        </td>
        <td>
          <button ng-click="deleteOrder(order)" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
        </td>
      </tr>
    </tbody>
  </table>

</div> <!-- ng-controller -->

app/views/orders/new.html.erb
<h1>New Product</h1>

<%= render 'form', order: @order %>