config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users, skip: [:sessions]
# 	as :user do
# 	  get 'signin', to: 'devise/sessions#new', as: :new_user_session
# 	  post 'signin', to: 'devise/sessions#create', as: :user_session
# 	  match 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
# 	end
	
#   resources :users
#   resources :products
#     resources :orders, only: [:index, :show, :create, :destroy, :new, :edit ]

#   get 'static_pages/about'

#   get 'static_pages/contact'

#   get 'static_pages/index'
#   root 'static_pages#landing_page'

#   post 'static_pages/thank_you'
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end
Rails.application.routes.draw do

devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  
  root 'static_pages#landing_page'
  
  resources :products do
  resources :comments
  end
   resources :orders
  resources :users
  resources :payments

  get 'static_pages/about'
  get 'static_pages/contact'
  get 'static_pages/index'
  post 'static_pages/thank_you'
  post 'payments/create'
  get 'payments/create'
  get 'products/index'
  mount ActionCable.server => '/cable'

 # get '/products/:id', to: 'products#show'

  # default route
  # may go away in future versions of Rails
  # get ':controller (/:action (/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikes</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--  <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
      <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Raleway:400,700" rel="stylesheet"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" >
            <!--<span class="sr-only">Toggle navigation</span>-->
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Bike Shop", root_path , class: "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse " id="bs-example-navbar-collapse-1 ">
          <!-- Sign up Log in -->
          <ul div class="navlog navbar-form navbar-right ">
            <li><% if user_signed_in? %>
              <%= link_to('Edit User', edit_user_registration_path, :method => :get, class:"btn btn-default" ) %>
              <% else %>
              <%= link_to('Register', new_user_registration_path, :method => :get, class:"btn btn-default" ) %>
              <% end %>    
              <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete, class:"btn btn-default" ) %>
              <% else %>
              <%= link_to('Login', new_user_session_path, :method => :get, class:"btn btn-default" ) %>
              <% end %>
            </li>
          </ul>
          <!-- Search Box -->
          <%= form_tag("/products", method: "get", class:"navbar-form navbar-right") do %> 
          <div class="form-group">
            <%= label_tag(:q, "Search for:", class:"hidden") %>
            <%= text_field_tag(:q, "", type:"text", class:"form-control", placeholder:"Search") %>
          </div>
          <%= submit_tag("Search", class:"btn btn-default") %>
          <% end %>
          <ul class="nav navbar-nav navbar-left">
            <% if user_signed_in? %>
            <li class="active"><%= link_to "Bikes", products_path %></li>
            <li class="active"><%= link_to "About", static_pages_about_path %></li>
            <li class="active"><%= link_to "Contact", static_pages_contact_path %></li>
            <li class="active"><%= link_to "Orders", orders_url %></li>
            <li class="active"><%= link_to "Users", users_path %></li>
            <% else %>
            <li class="active"><%= link_to "Bikes", products_path %></li>
            <li class="active"><%= link_to "About", static_pages_about_path %></li>
            <li class="active"><%= link_to "Contact", static_pages_contact_path %></li>
            <% end %>  
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
    <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p id="alert" class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <footer class="footer-d">
      <div class="footer-right">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>
      </div>
      <div class="footer-copy">
        <p>Berlin Bikes &copy; 2017</p>
      </div>
    </footer>
  </body>
</html>